version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=SWAT
      - POSTGRES_PASSWORD=1234
      - PGHOST=db
  web:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000