# Generated by Django 4.0.1 on 2022-05-27 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('google_user_id', models.CharField(default='EMPTY', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=100000.0, max_digits=1000)),
                ('portfolio_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('ownedStocks', models.JSONField(default=dict, null=True)),
                ('watchList', models.JSONField(default=dict, null=True)),
                ('transaction_history', models.JSONField(default=dict, null=True)),
                ('portfolio_value_history', models.JSONField(default=dict, null=True)),
                ('start_date', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
