# Generated by Django 4.0.1 on 2022-05-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(default='INVALID', max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='google_user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
