# Generated by Django 4.0.1 on 2022-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_ownedstocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ownedStocks',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
