# Generated by Django 3.2.5 on 2022-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_email_alter_account_google_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='google_user_id',
            field=models.CharField(default='heyo', max_length=50),
        ),
    ]
