# Generated by Django 4.0.1 on 2022-03-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_ownedstocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='portfolio_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
