# Generated by Django 3.2.5 on 2022-02-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='portfolio_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000000000),
        ),
    ]
