# Generated by Django 4.0.1 on 2022-03-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_ownedstocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='portfolio_value_history',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_history',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='watchList',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
