# Generated by Django 4.0.1 on 2022-02-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_portfolio_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ownedStocks',
            field=models.JSONField(null=True),
        ),
    ]
