# Generated by Django 4.0.1 on 2022-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_ownedstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='start_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
