# Generated by Django 4.0.1 on 2022-02-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_history',
            field=models.JSONField(null=True),
        ),
    ]
