# Generated by Django 4.0.1 on 2022-02-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='watchList',
            field=models.JSONField(null=True),
        ),
    ]
