# Generated by Django 4.0.1 on 2022-02-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='portfolio_value_history',
            field=models.JSONField(null=True),
        ),
    ]
