# Generated by Django 3.2.5 on 2022-05-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('percent_change', models.DecimalField(decimal_places=2, max_digits=30)),
                ('change_direction', models.BooleanField()),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30)),
                ('pe_ratio', models.DecimalField(decimal_places=2, max_digits=30)),
                ('dividend_yield', models.DecimalField(decimal_places=2, max_digits=30)),
                ('average_volume', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('high_today', models.DecimalField(decimal_places=2, max_digits=30)),
                ('low_today', models.DecimalField(decimal_places=2, max_digits=30)),
                ('ft_week_high', models.DecimalField(decimal_places=2, max_digits=30)),
                ('ft_week_low', models.DecimalField(decimal_places=2, max_digits=30)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
